esphome:
  name: technopark
  includes: 
    - grid.h

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "API_PASS"

ota:
  - platform: esphome
    password: "API_PASS"

wifi:
  ssid: "WIFI_NAME"
  password: "WIFI_PASS"

  manual_ip:
    static_ip: 192.168.0.197
    subnet: 255.255.255.0
    gateway: 192.168.0.254

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "Technopark Fallback Hotspot"
  #  password: "FALLBACK_PASS"

web_server:
  port: 80
  ota: False


# https://esphome.io/components/light/neopixelbus
# https://esphome.io/components/light/partition

light:
  - platform: neopixelbus
    id: technopark
    name: "technopark"
    variant: ws2812x
    type: RGB
    pin: GPIO12
    num_leds: 212
    
  - platform: partition
    name: "letter_01_T"
    segments: 
      - id: technopark
        from: 0
        to: 15

  - platform: partition
    name: "letter_02_E"
    segments: 
      - id: technopark
        from: 16
        to: 37

  - platform: partition
    name: "letter_03_C"
    segments: 
      - id: technopark
        from: 38
        to: 53

  - platform: partition
    name: "letter_04_H"
    segments: 
      - id: technopark
        from: 54
        to: 77

  - platform: partition
    name: "letter_05_N"
    segments: 
      - id: technopark
        from: 78
        to: 105

  - platform: partition
    name: "letter_06_O"
    segments: 
      - id: technopark
        from: 106
        to: 125

  - platform: partition
    name: "letter_07_P"
    segments: 
      - id: technopark
        from: 126
        to: 145

  - platform: partition
    name: "letter_08_A"
    segments: 
      - id: technopark
        from: 146
        to: 169

  - platform: partition
    name: "letter_09_R"
    segments: 
      - id: technopark
        from: 170
        to: 190

  - platform: partition
    name: "letter_10_K"
    id: letter_10_K
    segments: 
      - id: technopark
        from: 191
        to: 211


switch:
  - platform: gpio
    name: "led2"
    pin: GPIO02
    id: gpio_d2

  - platform: template
    name: "All Red"
    optimistic: True
    turn_on_action:
      - light.addressable_set:
          id: technopark
          red: 100%
    turn_off_action:
      - light.addressable_set:
          id: technopark
          red: 0%

  - platform: template
    name: "All Green"
    optimistic: True
    turn_on_action:
      - light.addressable_set:
          id: technopark
          green: 100%
    turn_off_action:
      - light.addressable_set:
          id: technopark
          green: 0%

  - platform: template
    name: "All Blue"
    optimistic: True
    turn_on_action:
      - light.addressable_set:
          id: technopark
          blue: 100%
    turn_off_action:
      - light.addressable_set:
          id: technopark
          blue: 0%

            
    
# https://esphome.io/components/display/addressable_light.html
# https://esphome.io/automations/templates#config-lambda

#display:
#  - platform: addressable_light
#    id: letters
#    addressable_light_id: technopark
#    width: 62
#    height: 10
#    update_interval: 16ms
#    pixel_mapper: |-
#          //return LETTER_GRID[y][x];
#          return 78;
#    lambda: |-
#          Color red = Color(0xFF0000);
#          Color green = Color(0x00FF00);
#          Color blue = Color(0x0000FF);
#
#          //it.draw_pixel_at(3, 0);
#          it.line(0,0, 62, 0);

